version: "3.8"

services:
  flask-app:
    image: korinnyi/flask-app:latest
    command: gunicorn --bind :4200 --workers 3 -t 60 flask_app.wsgi:application
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app_network
      - nginx_network
      - database_network

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask_app
      - POSTGRES_PASSWORD=flask_app
      - POSTGRES_DB=flask_app
    networks:
      - database_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - app

networks:
  app_network:
    name: app_network
    driver: bridge
  nginx_network:
    name: nginx_network
    driver: bridge
  database_network:
    name: database_network
    driver: bridge

volumes:
  postgres_data:
